/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Datos.Campos;
import Logica.CreadorTabla;
import Logica.InicializadorArchivo;
import Logica.GestorArchivo;
import static Logica.GestorArchivo.LongitudesCampos;
import Logica.GestorRegistro;
import Patrones.TemplateSerializar;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Emily Arteaga, Jefferson Arias, Christian Salinas
 * Programacion 3: Estructura de Archivo - Universidad de Cuenca
 */
public class RecuperarDatos extends javax.swing.JFrame {

    private static String PATH_ARCHIVO = "archivos/META_BD.csv";
    public String histo=null;
    /**
     * Creates new form RecuperarDatos
     */
    public RecuperarDatos() {
        initComponents();
        setLocationRelativeTo(null);
        fondoPane();
    }
    
    private void showVentanaPrincipal() throws IOException {
        Principal ventana = new Principal();
        ventana.setVisible(true);
        ventana.setHistorial(histo);
    }
    public void fondoPane(){
        UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.BLACK);
        UI.put("Panel.background", Color.BLACK);
        UI.put("OptionPane.messageForeground", Color.white);
    }
    public String recuperarHist()throws FileNotFoundException, IOException, ClassNotFoundException{
        String histor="";
        try (ObjectInputStream input_hist = new ObjectInputStream(new FileInputStream("serializar/Principal_Historial.dat"))) {
            histo=(String)input_hist.readObject();
            input_hist.close();
        }catch(IOException x){
            
        }
        return histor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bNuevos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperar Datos");
        setBackground(new java.awt.Color(0, 0, 51));
        setLocationByPlatform(true);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Desea recuperar los datos anteriores?");

        bAceptar.setBackground(new java.awt.Color(0, 0, 51));
        bAceptar.setForeground(new java.awt.Color(255, 255, 255));
        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bNuevos.setBackground(new java.awt.Color(0, 0, 51));
        bNuevos.setForeground(new java.awt.Color(255, 255, 255));
        bNuevos.setText("Nuevos");
        bNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevosActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAzulMosaico.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bNuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAceptar)
                    .addComponent(bNuevos)))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        
        try {
            
            if ( InicializadorArchivo.recuperarDatos(PATH_ARCHIVO) ) {
                    //            GestorArchivo.desSerializarGestorArchivo();
                //CreadorTabla.DesSerializar_CreadorTabla();\
                    //           GestorRegistro.deserializar_GestorRegistro();
                TemplateSerializar cargar = new GestorArchivo();
                cargar.Deserializar();
                //CreadorTabla.DesSerializar_CreadorTabla();
                histo=recuperarHist();
                JOptionPane.showMessageDialog(null, "Se ha recuperado los datos");
                
            } else {
                JOptionPane.showMessageDialog(null, "Se ha creado un nuevo archivo");
            }
            this.dispose();
            showVentanaPrincipal();
        } catch (IOException ex) {
            Logger.getLogger(RecuperarDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecuperarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevosActionPerformed
        
        try {
            this.dispose();
            if ( InicializadorArchivo.sobreescribirDatos(PATH_ARCHIVO) ) {
                histo=null;
                JOptionPane.showMessageDialog(null, "Se ha sobreescrito el archivo anterior", null, JOptionPane.PLAIN_MESSAGE);          
            } else {
                histo=null;
                JOptionPane.showMessageDialog(null, "Se ha creado un nuevo archivo", null, JOptionPane.PLAIN_MESSAGE);   
            }
            showVentanaPrincipal();
        } catch (IOException ex) {
            Logger.getLogger(RecuperarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bNuevosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bNuevos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
